name: 02 - Workflow Events
on: 
  
  pull_requests:
  workflow_dispatch:
  schedule:
    - cron: '*/5****'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - name:
        run: |
          echo "Event name: ${{ github.event_name }}"

          